# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2a21225cb579b18f848496adaac92a8757018749dcfda7d3fc74ee3477fff5dab6e33187f038dd5ce3c432b615a27e6e54d7c4940f4ee489c5aebdd7d920e76

test:
  secret_key_base: ba96d4a5a00321fffe3469cc4ff8305ccb0ea797412d8f6202234e1bec7288ea3d116889d1bc0f3eb07e57daf59e8176f284fdc0c1084eb07459adf81db729d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
